### ISSUE TITLE
return ボタンを押してもキーボードが閉じない

### ISSUE THREAD

**Issue by yuzumikan15** [anthony1618/Nanitabe#27]
`InitialSettingViewController` の `locationTextField` を押すとキーボードがでてきますが，return を押しても閉じないのは delegate method の書き忘れな気がします．

**Comment by anthony1618** [comment]
@yuzumikan15 LocationTextFieldは入力しないので、enabledを書き忘れています。

**Comment by yuzumikan15** [comment]
了解です．入力がいらないのであれば UILabel でもよかったかもです．
