### ISSUE TITLE
料金設定の下限と上限の連動について

### ISSUE THREAD

**Issue by yuzumikan15** [anthony1618/Nanitabe#28]
[これ](https://github.com/anthony1618/Nanitabe/blob/master/Nanitabe/ViewController/InitialSettingViewController.swift#L76)
は例えば `minPrice = 0` && `maxPrice = 3000` みたいな設定はできないと思うのですが，仕様ですか？(下限と上限の差は1000円であるという理由や調査がどこかにあれば聞きたいです)

**Comment by T-Masaaki** [comment]
@yuzumikan15 
仕様の共有ミスで、バグが仕様になってしまいました。
本来はminPrice = 0 && maxPrice = 3000みたいな設定もできるはずでした。
`InitialSettingViewController.swift`の
```swift
func pickerView(pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String? {
        switch component {
        case 0:
            return minPriceValue[row]
        case 1:
            return maxPriceValue[row]
        default: break
        }
        return ""
    }```
がバグのコードです。
このコードに合わせて実装してしまいました。

**Comment by yuzumikan15** [comment]
了解です :+1:
