### ISSUE TITLE
Optional 変数について

### ISSUE THREAD

**Issue by yuzumikan15** [anthony1618/Nanitabe#30]
https://github.com/anthony1618/Nanitabe/blob/master/Nanitabe/ViewController/DishesViewController.swift#L29

latitude, longitude に ! をつけた理由を知りたいです．

https://github.com/anthony1618/Nanitabe/blob/master/Nanitabe/ViewController/DishesViewController.swift#L29

ここでそれぞれ代入してますが，この時点で nil check を先にしておけばよかったのではないかと思いました．ここでは nil check をしていないのに L196 では guard を入れているのがよく分からないです．

```
guard let latitude = manager.location!.coordinate.latitude, let longitude = manager.location!.coordinate.longitude else {
            return
        }
        
initialSetting.latitude = latitude
initialSetting.longitude = longitude

initialSetting.positionalInfoToAddress(latitude, logitude: longitude) { address, error in
...
```

とかではダメでしょうか？

**Comment by anthony1618** [comment]
確かに、冗長になってますね。
そちらのほうがよいです.ありがとうございます:bow:
