### ISSUE TITLE
? をやめた理由

### ISSUE THREAD

**Issue by yuzumikan15** [anthony1618/Nanitabe#31]
コミットにコメントもしたのですが全部 issue にまとめた方がいいかと思ってこっちにも書きます．コミットの方で返信くれていたら二度手間になってしまいごめんなさい…

https://github.com/anthony1618/Nanitabe/blob/master/Nanitabe/ViewController/DishesViewController.swift#L31

昨日見たときはこの辺の変数は全部 `?` になっていたと思うのですがやめた理由を教えてください．

**Comment by anthony1618** [comment]
Optional型の変数に！をつけるのがあまりよくないと聞いて、勘違いしておりました。
オプショナル型で宣言してif letまたはguardでアンラップするのがよいですか？？

**Comment by yuzumikan15** [comment]
私はよく分からない初期値を入れるくらいなら `var + ?` を使って guard で nil check をします．一番危険なのは `var + !` で，unwrap の際に if let や guard を使わないで `!` を使うときは必ず nil にならないという確証を得てからにします (UIButton とかは storyboard から引っ張ってくると `!` になるのでそれはそのままにしておく，とかその程度です)．今回の場合はもともと `var + ?` になっていたのでそのままでよかったんじゃないかなと思いました．

あと全然関係ないですが，guard に関して，JSON の例外処理なんかも guard で書くのが best practice のようだと一昨日 try! Swift の Organizer が言っていたので参考にしてください :+1:

**Comment by anthony1618** [comment]
なるほど、ありがとうございます！ :bow:
