### ISSUE TITLE
レストラン情報の画像が null なのはバグ？

### ISSUE THREAD

**Issue by yuzumikan15** [anthony1618/Nanitabe#33]
RestaurantsViewController にのってる画像，返ってくる JSON の image のところに URL とかあるのかなって思ったんだけど全部 null になってます．これは取得できるように書いてるけど取得できていないのか，間に合わなくて 全部 null にしているのかどっちですか？

**Comment by yuzumikan15** [comment]
環境
iPhone 6s, iOS 9.2.1

参考画像
https://gyazo.com/01f0db8573be4fc34d49a17176f05667

**Comment by T-Masaaki** [comment]
@yuzumikan15 
間に合わなくてnullにしています。将来的にはお店の画像を表示する画面も用意したほうがいいかな、と思ったので準備しています。mustの実装ではそこまでできそうではなかったので、データを集めるときにお店の画像はスキップしました。

**Comment by yuzumikan15** [comment]
なるほど，want だったのですね，すみません．

ちなみに
- DishesViewController で「結果0件」がなかなか increment されないのは私の使い方の問題でしょうか？
- RestaurantsViewController はおそらくローカルで作ったもののみが表示されてるのですがこれも間に合わなかった？

(エラーメッセージはこんなのが出てきます)
https://gyazo.com/1bbcd9352d8dd2644e03ec2e3e5afe46

**Comment by T-Masaaki** [comment]
@yuzumikan15 
すみません。どちらも実装が間に合いませんでした。
使い方の問題ではありません。

**Comment by yuzumikan15** [comment]
いえいえ，want なら仕方ないです．
