### ISSUE TITLE
Dishes Viewに表示する料理の文字情報の仕様が決まってない

### ISSUE THREAD

**Issue by T-Masaaki** [anthony1618/Nanitabe#8]
料理の写真の下？料理の写真に重ねる？
項目はこんな感じかな？
- 料理名
- 値段
- お店の名前

**Comment by anthony1618** [comment]
[![LGTM](http://lgtm.in/p/AKKDUTyIn)](http://lgtm.in/i/AKKDUTyIn)

**Comment by anthony1618** [comment]
## TinderUIに表示させる項目
- 料理の写真
- 料理名
- 値段
